type ItemType = {
    id: number;
    deleted: boolean;
    description: string;
    isIot: boolean | null;
    makerCode: string | null;
    readingMethod: string;
    readingMethodCode: string;
    selected: boolean;
};

export const mockedItems: Array<ItemType> = [
    {
        id: 1,
        readingMethod: "ITRON PUNTO DE ACCESO",
        readingMethodCode: "ACTG",
        makerCode: "D",
        description: "ITRON / EVERBLU",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 10,
        readingMethod: "SAPPEL GATEWAY",
        readingMethodCode: "SAPG",
        makerCode: "C",
        description: "SAPPEL / IZAR",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 11,
        readingMethod: "CONTAZARA GATEWAY",
        readingMethodCode: "CTZG",
        makerCode: "K",
        description: "CONTAZARA / RIAC",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 2,
        readingMethod: "TEST TECHNOLOGY 1",
        readingMethodCode: "RM1",
        makerCode: "MC1",
        description: "DESC TEST TECH 1",
        isIot: true,
        deleted: false,
        selected: false,
    },
    {
        id: 4,
        readingMethod: "CTZG",
        readingMethodCode: "CTZG",
        makerCode: null,
        description: "CONTAZARA GATEWAY",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 5,
        readingMethod: "ELSG",
        readingMethodCode: "ELSG",
        makerCode: null,
        description: "ELSTER GATEWAY",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 6,
        readingMethod: "IKOG",
        readingMethodCode: "IKOG",
        makerCode: null,
        description: "IKOR ESTACION BASE",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 7,
        readingMethod: "SAPG",
        readingMethodCode: "SAPG",
        makerCode: null,
        description: "SAPPEL GATEWAY",
        isIot: null,
        deleted: false,
        selected: false,
    },
    {
        id: 8,
        readingMethod: "ABEG",
        readingMethodCode: "ABEG",
        makerCode: null,
        description: "ABERING CONCENTRADOR",
        isIot: null,
        deleted: false,
        selected: false,
    },
    {
        id: 9,
        readingMethod: "ABLG",
        readingMethodCode: "ABLG",
        makerCode: null,
        description: "ABERING LoRaWAN",
        isIot: null,
        deleted: false,
        selected: false,
    },
    {
        id: 12,
        readingMethod: "SAPPEL",
        readingMethodCode: "SAPP",
        makerCode: "C",
        description: "SAPPEL",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 13,
        readingMethod: "ACTARIS",
        readingMethodCode: "ACTA",
        makerCode: "D",
        description: "ITRON",
        isIot: false,
        deleted: false,
        selected: false,
    },
    {
        id: 3,
        readingMethod: "OTHERS ITS AN EXAMPLE OF WHAT HAPPENS IN CASE OF A VERY LONG TEXT ITEM",
        readingMethodCode: "OTHERS ITS AN EXAMPLE OF WHAT HAPPENS IN CASE OF A VERY LONG TEXT ITEM",
        makerCode: null,
        description: "OTHERS ITS AN EXAMPLE OF WHAT HAPPENS IN CASE OF A VERY LONG TEXT ITEM",
        isIot: false,
        deleted: false,
        selected: false,
    }
];

export const mockedHierarchy: any = {
    value: "22-hierarchy",
    label: "JERARQUÍA MIGRACIÓN",
    type: "hierarchy",
    id: 22,
    children: [
        {
            label: "AIGÜES DE SAGUNT",
            value: "4720-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4720,
            parentId: null,
            tag: null,
            alarms: null,
            children: [
                {
                    label: "Enric1",
                    value: "4838-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4838,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "Enric2",
                    value: "4839-dma",
                    icon: "dma",
                    favourite: true,
                    sensorizable: true,
                    id: 4839,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "Enric3",
                    value: "4840-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4840,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "Enric4",
                    value: "4841-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4841,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "Enric6",
                    value: "4902-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4902,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "GEMA",
                    value: "4923-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4923,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "N1",
                    value: "4825-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4825,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [],
                },
                {
                    label: "N2",
                    value: "4826-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4826,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "HIJO-1",
                            value: "4827-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4827,
                            parentId: 4826,
                            tag: null,
                            alarms: null,
                            children: [
                                {
                                    label: "NUEVO-NIVEL",
                                    value: "4829-dma",
                                    icon: "dma",
                                    favourite: false,
                                    sensorizable: true,
                                    id: 4829,
                                    parentId: 4827,
                                    tag: null,
                                    alarms: null,
                                    children: [
                                        {
                                            label: "Enric5",
                                            value: "4842-dma",
                                            icon: "dma",
                                            favourite: false,
                                            sensorizable: true,
                                            id: 4842,
                                            parentId: 4829,
                                            tag: null,
                                            alarms: null,
                                            children: [],
                                        },
                                    ],
                                },
                            ],
                        },
                        {
                            label: "HIJO-2",
                            value: "4828-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4828,
                            parentId: 4826,
                            tag: null,
                            alarms: null,
                            children: [
                                {
                                    label: "NUEVO-NIVEL",
                                    value: "4830-dma",
                                    icon: "dma",
                                    favourite: false,
                                    sensorizable: true,
                                    id: 4830,
                                    parentId: 4828,
                                    tag: null,
                                    alarms: null,
                                    children: [],
                                },
                            ],
                        },
                    ],
                },
                {
                    label: "Port Sagunt",
                    value: "4144-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4144,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "Sp-01",
                            value: "4145-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4145,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-02",
                            value: "4146-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4146,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-03",
                            value: "4148-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4148,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-04",
                            value: "4175-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4175,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-05",
                            value: "4177-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4177,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-06",
                            value: "4179-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4179,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-07",
                            value: "4180-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4180,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-08",
                            value: "4181-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4181,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-09",
                            value: "4182-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4182,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-10",
                            value: "4183-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4183,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-11",
                            value: "4184-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4184,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-12",
                            value: "4185-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4185,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-13",
                            value: "4186-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4186,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-13.1 Churruca",
                            value: "4187-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4187,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-14",
                            value: "4188-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4188,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-15",
                            value: "4189-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4189,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-16",
                            value: "4190-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4190,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-17",
                            value: "4193-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4193,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-18.1 Sepes",
                            value: "4213-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4213,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-18.2 Ingruinsa",
                            value: "4214-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4214,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-19",
                            value: "4196-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4196,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-Parc Sagunt",
                            value: "4197-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4197,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-Pol. Cami La Mar",
                            value: "4199-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4199,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-Polideportivo",
                            value: "4200-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4200,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-Traída Cota 55",
                            value: "4201-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4201,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-Traída Etap A Parc Sagunt",
                            value: "4202-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4202,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sp-Traída Sectores",
                            value: "4203-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4203,
                            parentId: 4144,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
                {
                    label: "Sagunt",
                    value: "4775-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4775,
                    parentId: 4720,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "S1 SANTS DE LA PEDRA",
                            value: "4776-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4776,
                            parentId: 4775,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "S2.1 EMILIO LLOPIS",
                            value: "4777-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4777,
                            parentId: 4775,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "S2.2 BAJO VIAS",
                            value: "4779-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4779,
                            parentId: 4775,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "S3.1 GILET",
                            value: "4780-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4780,
                            parentId: 4775,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "S3.2 CLOT DEL MORO",
                            value: "4784-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4784,
                            parentId: 4775,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "S4 NORTE PALANCIA",
                            value: "4785-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4785,
                            parentId: 4775,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "DIRECCIÓN CATALUÑA",
            value: "4719-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4719,
            parentId: null,
            tag: null,
            alarms: null,
            children: [
                {
                    label: "Collbató",
                    value: "4272-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4272,
                    parentId: 4719,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "Sector 1- Dipòsit Can Dalmases Ii",
                            value: "4273-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4273,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 10- Can Guineu",
                            value: "4275-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4275,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 11 - La Ermita",
                            value: "4276-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4276,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label:
                                "Sector 12,13,14 - Pujolet 1,2,3 (Sector Únic)*",
                            value: "4277-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4277,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 15 - Parellades",
                            value: "4278-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4278,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 16 - La Creu",
                            value: "4279-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4279,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 17 - La Fumada",
                            value: "4280-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4280,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 18 - Lladó",
                            value: "4281-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4281,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 19 - La Autovía",
                            value: "4282-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4282,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 2- Eada",
                            value: "4274-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4274,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 20 - Bosc D'En Missé",
                            value: "4283-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4283,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 3 - Pierola /Gandesa",
                            value: "4284-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4284,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 4 - Pierola/Papiol",
                            value: "4285-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4285,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 5 - Can Migrat",
                            value: "4286-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4286,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 6 - Montserrat/Pompeu Fabra",
                            value: "4287-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4287,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 7 - Montserrat/Postas",
                            value: "4288-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4288,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 8 - Dipòsit Can Feliu",
                            value: "4289-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4289,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 9 - P.I. Ginesteres",
                            value: "4290-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4290,
                            parentId: 4272,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "DIRECCIÓN ZONA L'HORTA",
            value: "4718-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4718,
            parentId: null,
            tag: null,
            alarms: null,
            children: [
                {
                    label: "Albalat Dels Sorells",
                    value: "3598-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 3598,
                    parentId: 4718,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "Ayuntamiento",
                            value: "3599-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 3599,
                            parentId: 3598,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Industrial",
                            value: "3600-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 3600,
                            parentId: 3598,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Mestre Serrano",
                            value: "3601-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 3601,
                            parentId: 3598,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Planta Osmosis",
                            value: "3602-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 3602,
                            parentId: 3598,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Riego Planta",
                            value: "3603-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 3603,
                            parentId: 3598,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
                {
                    label: "FUENTE DEL JARRO",
                    value: "4722-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4722,
                    parentId: 4718,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "2ª FASE ALTA",
                            value: "4723-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4723,
                            parentId: 4722,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "2ª FASE BAJA",
                            value: "4724-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4724,
                            parentId: 4722,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "C/ ONTINYENT-CIUDAD DE LIRIA",
                            value: "4725-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4725,
                            parentId: 4722,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "CIUDAD DE ONDA",
                            value: "4726-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4726,
                            parentId: 4722,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "POLIGONO EL MOLI",
                            value: "4727-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4727,
                            parentId: 4722,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "ZONA CENTRAL-C/VILLA DE MADRID",
                            value: "4728-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4728,
                            parentId: 4722,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
                {
                    label: "Quart de Poblet",
                    value: "4824-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4824,
                    parentId: 4718,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "Sector 4",
                            value: "4945-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4945,
                            parentId: 4824,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 5",
                            value: "4949-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4949,
                            parentId: 4824,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Sector 5 Polideportivo",
                            value: "4814-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4814,
                            parentId: 4824,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
                {
                    label: "Rafelbunyol",
                    value: "4787-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4787,
                    parentId: 4718,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "01_Bobalar Ronda Oeste",
                            value: "4788-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4788,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "02_Estació",
                            value: "4789-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4789,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "03_Industrial Poble",
                            value: "4790-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4790,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "04_José María Llopis",
                            value: "4791-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4791,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "05_Vicente Soriano",
                            value: "4792-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4792,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "06_SADA",
                            value: "4794-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4794,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "07_Lladró",
                            value: "4793-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4793,
                            parentId: 4787,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "GANDÍA AP",
            value: "4721-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4721,
            parentId: null,
            tag: null,
            alarms: null,
            children: [
                {
                    label: "Daimús",
                    value: "4768-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4768,
                    parentId: 4721,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "01 LA MAR",
                            value: "4773-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4773,
                            parentId: 4768,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "02 REGULADORA",
                            value: "4774-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4774,
                            parentId: 4768,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "03 FLAMINGO",
                            value: "4772-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4772,
                            parentId: 4768,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "04 POLIGON",
                            value: "4771-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4771,
                            parentId: 4768,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "05 ESGLESIA",
                            value: "4770-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4770,
                            parentId: 4768,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
                {
                    label: "Gandía",
                    value: "4294-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4294,
                    parentId: 4721,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "01_Alcodar",
                            value: "4295-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4295,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "02_Av. De La Mar - Furs",
                            value: "4299-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4299,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "03_Beniopa",
                            value: "4300-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4300,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "04_Sant Pere",
                            value: "4301-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4301,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "05_Grau Vell",
                            value: "4302-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4302,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "06_Beniopa Passeig",
                            value: "4303-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4303,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "07 Republica Argentina 1",
                            value: "4304-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4304,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "09_Grau Poliesportiu",
                            value: "4305-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4305,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "11_Ronda De L'Anella ",
                            value: "4306-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4306,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "12 República Argentina Ii",
                            value: "4307-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4307,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "13_Benirredrà",
                            value: "4308-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4308,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "14_Cases Noves",
                            value: "4309-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4309,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "15_Sant Nicolau",
                            value: "4310-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4310,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "19_Pellers Sant Josep",
                            value: "4311-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4311,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "20_Corea",
                            value: "4312-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4312,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "22-Hospital Vell",
                            value: "4313-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4313,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "29_Raval - Prado",
                            value: "4314-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4314,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "30_Raval Rafelcofer",
                            value: "4315-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4315,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "32_Centre Històric",
                            value: "4316-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4316,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "33_Abad Sola Ferrocarril",
                            value: "4317-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4317,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "35_Serpis",
                            value: "4318-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4318,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "46_Centre - Ajuntament",
                            value: "4319-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4319,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "47_La Vital",
                            value: "4322-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4322,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "50_Benipeixcar",
                            value: "4320-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4320,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "54 Nueva Argentina",
                            value: "4321-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4321,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_24_Traida Marxuquera",
                            value: "4323-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4323,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_25_Xauxa",
                            value: "4325-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4325,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_26_Mollo 1",
                            value: "4328-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4328,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_27_Mollo 2",
                            value: "4327-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4327,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_28_Mollo 3",
                            value: "4329-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4329,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_37_Montesol",
                            value: "4330-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4330,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_38_Ermita I",
                            value: "4331-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4331,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_39_Ermita Ii",
                            value: "4332-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4332,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_40_Camí Pinet",
                            value: "4333-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4333,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Marxu_41_Barranc Blanc",
                            value: "4334-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4334,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_08_Kentucky",
                            value: "4335-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4335,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_10_Parc Clot De La Mota",
                            value: "4340-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4340,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_16_Verge - Av. Pau",
                            value: "4338-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4338,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_17_Plaça Castell Sidartha",
                            value: "4339-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4339,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_18 Comtat - Aragó",
                            value: "4348-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4348,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_34_Rafalcaid",
                            value: "4347-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4347,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_42_Degans Universitat",
                            value: "4346-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4346,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_44_Illes Canàries - Camí Vell",
                            value: "4345-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4345,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_45_Comtat Av. Nord",
                            value: "4344-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4344,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_51_Àgora",
                            value: "4341-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4341,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_52_Armada Espanyola",
                            value: "4355-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4355,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "Playa_53_Ducal",
                            value: "4342-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4342,
                            parentId: 4294,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "Nodo LV 1",
            value: "4847-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4847,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
        {
            label: "Nodo Sergio",
            value: "4846-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4846,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
        {
            label: "Sacmex",
            value: "4851-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4851,
            parentId: null,
            tag: null,
            alarms: null,
            children: [
                {
                    label: "Benito Juárez",
                    value: "4853-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 4853,
                    parentId: 4851,
                    tag: null,
                    alarms: null,
                    children: [
                        {
                            label: "BJ-01",
                            value: "4854-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4854,
                            parentId: 4853,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "BJ-02",
                            value: "4866-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4866,
                            parentId: 4853,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                        {
                            label: "BJ-03",
                            value: "4867-dma",
                            icon: "dma",
                            favourite: false,
                            sensorizable: true,
                            id: 4867,
                            parentId: 4853,
                            tag: null,
                            alarms: null,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "nagisaTest",
            value: "4879-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4879,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
        {
            label: "test 0.12.0",
            value: "4926-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4926,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
        {
            label: "test-0.5.0",
            value: "4834-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4834,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
        {
            label: "test060",
            value: "4858-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4858,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
        {
            label: "test080",
            value: "4864-dma",
            icon: "dma",
            favourite: false,
            sensorizable: true,
            id: 4864,
            parentId: null,
            tag: null,
            alarms: null,
            children: [],
        },
    ],
};
