export { HeaderMenu } from './HeaderMenu'
export { Footer } from './Footer'
export { TitleMain } from './TitleMain'
export { SubHeaderMenu } from './SubHeaderMenu'
export { SubMenuContent } from './SubMenuContent'
export { MainCover } from './MainCover'