export const dateItems: any[] = [
    { id: 0, description: "dd/MM/yyyy", value: "DD/MM/YYYY", selected: true },
    { id: 1, description: "yyyy/MM/dd", value: "YYYY/MM/DD", selected: false },
    { id: 2, description: "yyyy-MM-dd", value: "YYYY-MM-DD", selected: false },
    { id: 3, description: "d/M/yyyy", value: "DD/MM/YYYY", selected: false },
    { id: 4, description: "dd/MM/yy", value: "DD/MM/YY", selected: false },
    { id: 5, description: "dd-MM-yyyy", value: "DD-MM-YYYY", selected: false },
    { id: 6, description: "dd.MM.yyyy", value: "DD.MM.YYYY", selected: false },
    { id: 7, description: "dd.MM.yy", value: "DD.MM.YY", selected: false },
    {
        id: 8,
        description: "d.M.yyyy 'г.'",
        value: "DD.MM.YYYY r.",
        selected: false,
    },
    { id: 9, description: "dd-MM-yy", value: "DD-MM-YY", selected: false },
    { id: 10, description: "yyyy/M/d", value: "YYYY/MM/DD", selected: false },
    { id: 11, description: "M/d/yyyy", value: "MM/DD/YYYY", selected: false },
    { id: 12, description: "d.M.yyyy.", value: "DD.MM.YYYY.", selected: false },
    { id: 13, description: "d.M.yyyy", value: "DD.MM.YYYY", selected: false },
    { id: 14, description: "yyyy.MM.dd", value: "YYYY.MM.DD", selected: false },
    {
        id: 15,
        description: "d. M. yyyy",
        value: "DD. MM. YYYY",
        selected: false,
    },
    { id: 16, description: "d/MM/yyyy", value: "DD/MM/YYYY", selected: false },
    { id: 17, description: "MM/dd/yyyy", value: "MM/DD/YYYY", selected: false },
    {
        id: 18,
        description: "d. M. yyyy.",
        value: "DD. MM. YYYY",
        selected: false,
    },
    {
        id: 19,
        description: "yyyy. MM. dd.",
        value: "YYYY. MM. DD.",
        selected: false,
    },
    { id: 20, description: "dd/MM yyyy", value: "DD/MM YYYY", selected: false },
    {
        id: 21,
        description: "yyyy. M. d.",
        value: "YYYY. MM. DD.",
        selected: false,
    },
    { id: 22, description: "d-MMM yy", value: "DD/MM/YYYY", selected: false },
    { id: 23, description: "dd.M.yyyy", value: "DD.MM.YYYY", selected: false },
    { id: 24, description: "d.MM.yyyy", value: "DD.MM.YYYY", selected: false },
    { id: 25, description: "d-M-yyyy", value: "DD-MM-YYYY", selected: false },
    {
        id: 26,
        description: "d. MM. yyyy",
        value: "D. MM. YYYY",
        selected: false,
    },
    {
        id: 27,
        description: "dd.MM.yyyy.",
        value: "DD.MM.YYYY",
        selected: false,
    },
    {
        id: 28,
        description: "dd.MM.yy 'ý.'",
        value: "DD.MM.YYYY ý.",
        selected: false,
    },
    { id: 29, description: "yyyy-M-d", value: "YYYY-MM-DD", selected: false },
    { id: 30, description: "d/M/yy", value: "DD/MM/YY", selected: false },
];

export const hourItems: any[] = [
    { id: 0, description: "HH:MM (24h)", value: "24", selected: true },
    { id: 1, description: "HH:MM (12h)", value: "12", selected: false },
];

export const dayItems: any[] = [
    { id: 0, description: "Lunes", value: "L", selected: true },
    { id: 1, description: "Martes", value: "M", selected: false },
    { id: 2, description: "Miércoles", value: "X", selected: false },
    { id: 3, description: "Jueves", value: "J", selected: false },
    { id: 4, description: "Viernes", value: "V", selected: false },
    { id: 5, description: "Sábado", value: "S", selected: false },
    { id: 6, description: "Domingo", value: "D", selected: false },
];
